### ISSUE TITLE
simulate vehicle location pings

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/movr#54]
simulate all active vehicles periodically phoning home with their locations

The below has an unacceptably high latency at the moment
```
for ride in active_rides: 
  movr.update_vehicle_location(ride['city'], ride['id'], datagen.address())
```

**Comment by nstewart** [comment]
https://github.com/cockroachdb/docs/issues/4295

https://github.com/cockroachdb/cockroach/pull/34295

**Comment by nstewart** [comment]
Going to add a new table for location history with ride_id + timestamp as the primary key

**Comment by jseldess** [comment]
An idea: Since this will be a separate table, and you plan to update each row frequently, you might consider creating a specific zone config for that table and dramatically reducing the gc window so that a buildup of mvcc history isn't a problem.

However, if `ride_id` has a foreign key relationship to `rides.id`, each update to the new table will still require an update to the `rides` table, so you may still have that mvcc issue, not sure.

**Comment by nstewart** [comment]
I won't be updating each row -- I'm adding each ping as a new record. This approach solves the MVCC problem.

Fixed with https://github.com/cockroachdb/movr/pull/66
